apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
  namespace: continuum-501f9a
  labels:
    app.kubernetes.io/instance: '501f9a'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
        app.kubernetes.io/instance: '501f9a'
    spec:
      runtimeClassName: contrast-cc
      containers:
        - name: secret-service
          image: 'ghcr.io/edgelesssys/privatemode/secret-service:v1.14.0@sha256:0844e716df7ee902de04b58c9b916f8c69583d2aaeff7c52f74fc99cf8f5c3e9'
          args:
            - '--etcd-host=secret-service-internal.continuum-501f9a.svc.cluster.local'
            - '--etcd-server-cert=/contrast/tls-config/certChain.pem'
            - '--etcd-server-key=/contrast/tls-config/key.pem'
            - '--etcd-ca=/contrast/tls-config/mesh-ca.pem'
          ports:
            - containerPort: 3000
            - containerPort: 3001
            - containerPort: 9000
            - containerPort: 2379
            - containerPort: 2380
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workload-codegen
  namespace: continuum-501f9a
  labels:
    app: workload-codegen
    app.kubernetes.io/instance: '501f9a'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-codegen
  serviceName: workload-codegen
  template:
    metadata:
      labels:
        app: workload-codegen
        app.kubernetes.io/instance: '501f9a'
        privatemode.edgeless.systems/needs-gpu: "true"
      annotations:
        io.katacontainers.config.hypervisor.default_memory: "64000"
        io.katacontainers.config.runtime.create_container_timeout: "1800"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: workload-codegen-sa
      runtimeClassName: contrast-cc
      initContainers:
        - name: attestation-agent
          image: ghcr.io/edgelesssys/privatemode/attestation-agent:v1.14.0@sha256:b6667a5a02239a1b9b459c71ce0f1eece59f5be8314f2907577a81c2d2a5cac2
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          command:
            - '/bin/sh'
            - '-c'
          args:
            - |
              ln -sf /usr/lib64/libnvidia-ml.so.550.90.07 /usr/lib64/libnvidia-ml.so.1 && \
              LD_PRELOAD=/usr/lib64/libcuda.so.1:usr/lib64/libnvidia-ml.so.1 attestation-agent \
                --gpu-debug=false \
                --gpu-secure-boot=true \
                --gpu-eat-version=EAT-21 \
                --gpu-driver-versions=535.104.05,535.129.03,550.90.07 \
                --gpu-vbios-versions=96.00.88.00.11,96.00.74.00.11,96.00.9F.00.04,96.00.74.00.1C
          securityContext:
            privileged: true
          resources:
            limits:
              "nvidia.com/GH100_H100_PCIE": 1
        - name: disk-mounter
          image: ghcr.io/edgelesssys/privatemode/disk-mounter:v1.14.0@sha256:2cafd9f586614ce88ba45b85ce44eb0d3e92dac141e276bfc6aa0fe24271b5ea
          args:
            - --root-hash=c6ab549d3ec1cb75d531886229825deec19e43e1dbc35480fd82a0517f04c14c
            - --device-path=/dev/modelweights
            - --mount-path=/mnt/modelweights
          restartPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: mount-dir
              mountPath: /mnt
              mountPropagation: Bidirectional
          volumeDevices:
            - name: modelweights
              devicePath: /dev/modelweights
      containers:
        - name: workload
          image: docker.io/vllm/vllm-openai:v0.8.2@sha256:61732e5aae863dc2e1df4c4a3e45a95d55b3991917b3bedc8bf1da5e077a4eb4
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /v1/models
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: LD_PRELOAD
              value: "/usr/lib/x86_64-linux-gnu/libcuda.so.1"
          args:
            - '--no-enable-prefix-caching'
            - '--host=0.0.0.0'
            - '--model=/mnt/modelweights'
            - '--served-model-name'
            - 'mistralai/Codestral-22B-v0.1'
            - '--disable-log-requests'
          volumeMounts:
            - name: mount-dir
              mountPath: /mnt
              mountPropagation: HostToContainer
          resources:
            limits:
              "nvidia.com/GH100_H100_PCIE": 1
        - name: inference-proxy
          image: ghcr.io/edgelesssys/privatemode/inference-proxy:v1.14.0@sha256:4374345f82c8e8b6c6b11cd36a523938e4e23459f2c0c8d4fcbfe9886359c031
          ports:
            - containerPort: 8085
          args:
            - --adapter-type=openai
            - --workload-address=127.0.0.1
            - --workload-port=8000
            - --secret-svc-address=secret-service-internal.continuum-501f9a.svc.cluster.local
            - '--etcd-member-cert=/contrast/tls-config/certChain.pem'
            - '--etcd-member-key=/contrast/tls-config/key.pem'
            - '--etcd-ca=/contrast/tls-config/mesh-ca.pem'
      volumes:
        - emptyDir: {}
          name: mount-dir
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      metadata:
        name: modelweights
        labels:
          app.kubernetes.io/instance: '501f9a'
      spec:
        storageClassName: mistralai-codestral-22b-v0-1
        volumeMode: Block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 46Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workload-textgen
  namespace: continuum-501f9a
  labels:
    app: workload-textgen
    app.kubernetes.io/instance: '501f9a'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-textgen
  serviceName: workload-textgen
  template:
    metadata:
      labels:
        app: workload-textgen
        app.kubernetes.io/instance: '501f9a'
        privatemode.edgeless.systems/needs-gpu: "true"
      annotations:
        io.katacontainers.config.hypervisor.default_memory: "64000"
        io.katacontainers.config.runtime.create_container_timeout: "1800"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: workload-textgen-sa
      runtimeClassName: contrast-cc
      initContainers:
        - name: attestation-agent
          image: ghcr.io/edgelesssys/privatemode/attestation-agent:v1.14.0@sha256:b6667a5a02239a1b9b459c71ce0f1eece59f5be8314f2907577a81c2d2a5cac2
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          command:
            - '/bin/sh'
            - '-c'
          args:
            - |
              ln -sf /usr/lib64/libnvidia-ml.so.550.90.07 /usr/lib64/libnvidia-ml.so.1 && \
              LD_PRELOAD=/usr/lib64/libcuda.so.1:usr/lib64/libnvidia-ml.so.1 attestation-agent \
                --gpu-debug=false \
                --gpu-secure-boot=true \
                --gpu-eat-version=EAT-21 \
                --gpu-driver-versions=535.104.05,535.129.03,550.90.07 \
                --gpu-vbios-versions=96.00.88.00.11,96.00.74.00.11,96.00.9F.00.04,96.00.74.00.1C
          securityContext:
            privileged: true
          resources:
            limits:
              "nvidia.com/GH100_H100_PCIE": 1
        - name: disk-mounter
          image: ghcr.io/edgelesssys/privatemode/disk-mounter:v1.14.0@sha256:2cafd9f586614ce88ba45b85ce44eb0d3e92dac141e276bfc6aa0fe24271b5ea
          args:
            - --root-hash=3a49ed30e4a637228b5d962c6b1fa508bad337ca73ef02cb9f0dcc7931fefad7
            - --device-path=/dev/modelweights
            - --mount-path=/mnt/modelweights
          restartPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: mount-dir
              mountPath: /mnt
              mountPropagation: Bidirectional
          volumeDevices:
            - name: modelweights
              devicePath: /dev/modelweights
      containers:
        - name: workload
          image: docker.io/vllm/vllm-openai:v0.8.2@sha256:61732e5aae863dc2e1df4c4a3e45a95d55b3991917b3bedc8bf1da5e077a4eb4
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /v1/models
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: LD_PRELOAD
              value: "/usr/lib/x86_64-linux-gnu/libcuda.so.1"
          args:
            - '--no-enable-prefix-caching'
            - '--host=0.0.0.0'
            - '--model=/mnt/modelweights'
            - '--served-model-name'
            - 'ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4'
            - 'latest'
            - '--disable-log-requests'
            - '--max-model-len=70000'
            - '--enable-auto-tool-choice'
            - '--tool-call-parser'
            - 'llama3_json'
          volumeMounts:
            - name: mount-dir
              mountPath: /mnt
              mountPropagation: HostToContainer
          resources:
            limits:
              "nvidia.com/GH100_H100_PCIE": 1
        - name: inference-proxy
          image: ghcr.io/edgelesssys/privatemode/inference-proxy:v1.14.0@sha256:4374345f82c8e8b6c6b11cd36a523938e4e23459f2c0c8d4fcbfe9886359c031
          ports:
            - containerPort: 8085
          args:
            - --adapter-type=openai
            - --workload-address=127.0.0.1
            - --workload-port=8000
            - --secret-svc-address=secret-service-internal.continuum-501f9a.svc.cluster.local
            - '--etcd-member-cert=/contrast/tls-config/certChain.pem'
            - '--etcd-member-key=/contrast/tls-config/key.pem'
            - '--etcd-ca=/contrast/tls-config/mesh-ca.pem'
      volumes:
        - emptyDir: {}
          name: mount-dir
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      metadata:
        name: modelweights
        labels:
          app.kubernetes.io/instance: '501f9a'
      spec:
        storageClassName: ibnzterrell-meta-llama-3-3-70b-instruct-awq-int4
        volumeMode: Block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 41Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured-api
  namespace: continuum-501f9a
  labels:
    app: unstructured-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unstructured-api
  template:
    metadata:
      labels:
        app: unstructured-api
        app.kubernetes.io/instance: '501f9a'
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "600"
    spec:
      runtimeClassName: contrast-cc
      containers:
        - name: unstructured-api
          image: 'quay.io/unstructured-io/unstructured-api:0.0.83@sha256:49b31365e2747d3a5f0fb4f33daf55569fd33e3bc63d3f3861b10b6af59f4fee'
          resources:
            requests:
              memory: "24Gi"
            limits:
              memory: "24Gi"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
        - name: inference-proxy
          image: ghcr.io/edgelesssys/privatemode/inference-proxy:v1.14.0@sha256:4374345f82c8e8b6c6b11cd36a523938e4e23459f2c0c8d4fcbfe9886359c031
          ports:
            - containerPort: 8085
          args:
            - --adapter-type=unencrypted
            - --workload-address=127.0.0.1
            - --workload-port=8000
            - --secret-svc-address=secret-service-internal.continuum-501f9a.svc.cluster.local
          volumeMounts:
            - name: etcd-pki
              mountPath: /var/run/continuum/etcd/pki
      volumes:
        - emptyDir: {}
          name: mount-dir
        - name: etcd-pki
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coordinator
  namespace: 'continuum-501f9a'
  labels:
    app.kubernetes.io/instance: '501f9a'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coordinator
  namespace: 'continuum-501f9a'
  labels:
    app.kubernetes.io/instance: '501f9a'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coordinator
  namespace: 'continuum-501f9a'
  labels:
    app.kubernetes.io/instance: '501f9a'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coordinator
subjects:
  - kind: ServiceAccount
    name: coordinator
    namespace: "continuum-501f9a"
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: 'continuum-501f9a'
  labels:
    app.kubernetes.io/instance: '501f9a'
spec:
  ports:
    - name: userapi
      port: 1313
      targetPort: 1313
    - name: meshapi
      port: 7777
      targetPort: 7777
    - name: default-userapi
      port: 443
      targetPort: 1313
  selector:
    app.kubernetes.io/name: coordinator
    app.kubernetes.io/instance: '501f9a'
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
  namespace: 'continuum-501f9a'
  labels:
    app.kubernetes.io/instance: '501f9a'
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coordinator
  serviceName: coordinator
  template:
    metadata:
      annotations:
        contrast.edgeless.systems/pod-role: coordinator
      labels:
        app.kubernetes.io/name: coordinator
        app.kubernetes.io/instance: '501f9a'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    contrast.edgeless.systems/pod-role: coordinator
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - image: ghcr.io/edgelesssys/contrast/coordinator:v1.7.0@sha256:94eed95eca7f497ae516c18343aca5a604142bd7a92318c41c7e0cd5e5b20bcb
          name: coordinator
          ports:
            - containerPort: 1313
              name: userapi
            - containerPort: 7777
              name: meshapi
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            tcpSocket:
              port: 1313
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeDevices:
            - devicePath: /dev/csi0
              name: state-device
      runtimeClassName: contrast-cc
      serviceAccountName: coordinator
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: state-device
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Block
