allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":false,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"privatemode.edgeless.systems/commit_hash":"a3c28ea93c041acfaadb85401ad6493749a5aa04","privatemode.edgeless.systems/disk_size_gb":"41","privatemode.edgeless.systems/model_source":"https://huggingface.co/ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4","privatemode.edgeless.systems/root_hash":"75b8d152c9e012fe24ab50a60346a8f874aa35091e1ead2045bf326a3aa0f67e"},"name":"ibnzterrell-meta-llama-3-3-70b-instruct-awq-int4"},"parameters":{"backingImage":"verity-disk-saoqsp","backingImageChecksum":"f6f928353813c73abc29e1fd25372001aef10642f96aa184d58d55ec4b2f709b4479f546cda012b62468efa715467f43db1d419c74bf24e4e5303b89d4867848","dataEngine":"v1","dataLocality":"strict-local","numberOfReplicas":"1","staleReplicaTimeout":"2880"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    privatemode.edgeless.systems/commit_hash: a3c28ea93c041acfaadb85401ad6493749a5aa04
    privatemode.edgeless.systems/disk_size_gb: "41"
    privatemode.edgeless.systems/model_source: https://huggingface.co/ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4
    privatemode.edgeless.systems/root_hash: 75b8d152c9e012fe24ab50a60346a8f874aa35091e1ead2045bf326a3aa0f67e
  creationTimestamp: "2025-08-25T08:32:38Z"
  name: ibnzterrell-meta-llama-3-3-70b-instruct-awq-int4
  resourceVersion: "4947278532"
  uid: 26b98368-36ed-4288-bbe7-6eeef6ce12e0
parameters:
  backingImage: verity-disk-saoqsp
  backingImageChecksum: f6f928353813c73abc29e1fd25372001aef10642f96aa184d58d55ec4b2f709b4479f546cda012b62468efa715467f43db1d419c74bf24e4e5303b89d4867848
  dataEngine: v1
  dataLocality: strict-local
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
