// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/gpl/proto/secret-service/userapi/userapi.proto

package userapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretsResponse) Reset() {
	*x = SetSecretsResponse{}
	mi := &file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretsResponse) ProtoMessage() {}

func (x *SetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretsResponse.ProtoReflect.Descriptor instead.
func (*SetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescGZIP(), []int{0}
}

// SetSecrets is used to set inference secrets.
type SetSecretsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets is a map of secret names to secret values.
	Secrets map[string][]byte `protobuf:"bytes,1,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// TimeToLive is the time in seconds that the secrets are valid for.
	// 0 or negative values means the secrets are valid indefinitely.
	TimeToLive    int64 `protobuf:"varint,2,opt,name=TimeToLive,proto3" json:"TimeToLive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretsRequest) Reset() {
	*x = SetSecretsRequest{}
	mi := &file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretsRequest) ProtoMessage() {}

func (x *SetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretsRequest.ProtoReflect.Descriptor instead.
func (*SetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescGZIP(), []int{1}
}

func (x *SetSecretsRequest) GetSecrets() map[string][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *SetSecretsRequest) GetTimeToLive() int64 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

var File_internal_gpl_proto_secret_service_userapi_userapi_proto protoreflect.FileDescriptor

const file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDesc = "" +
	"\n" +
	"7internal/gpl/proto/secret-service/userapi/userapi.proto\x12,edgelesssys.continuum.secret_service.userapi\"\x14\n" +
	"\x12SetSecretsResponse\"\xd7\x01\n" +
	"\x11SetSecretsRequest\x12f\n" +
	"\aSecrets\x18\x01 \x03(\v2L.edgelesssys.continuum.secret_service.userapi.SetSecretsRequest.SecretsEntryR\aSecrets\x12\x1e\n" +
	"\n" +
	"TimeToLive\x18\x02 \x01(\x03R\n" +
	"TimeToLive\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012\x9b\x01\n" +
	"\aUserAPI\x12\x8f\x01\n" +
	"\n" +
	"SetSecrets\x12?.edgelesssys.continuum.secret_service.userapi.SetSecretsRequest\x1a@.edgelesssys.continuum.secret_service.userapi.SetSecretsResponseBLZJgithub.com/edgelesssys/continuum/internal/gpl/proto/secret-service/userapib\x06proto3"

var (
	file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescOnce sync.Once
	file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescData []byte
)

func file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescGZIP() []byte {
	file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescOnce.Do(func() {
		file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDesc), len(file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDesc)))
	})
	return file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDescData
}

var file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_gpl_proto_secret_service_userapi_userapi_proto_goTypes = []any{
	(*SetSecretsResponse)(nil), // 0: edgelesssys.continuum.secret_service.userapi.SetSecretsResponse
	(*SetSecretsRequest)(nil),  // 1: edgelesssys.continuum.secret_service.userapi.SetSecretsRequest
	nil,                        // 2: edgelesssys.continuum.secret_service.userapi.SetSecretsRequest.SecretsEntry
}
var file_internal_gpl_proto_secret_service_userapi_userapi_proto_depIdxs = []int32{
	2, // 0: edgelesssys.continuum.secret_service.userapi.SetSecretsRequest.Secrets:type_name -> edgelesssys.continuum.secret_service.userapi.SetSecretsRequest.SecretsEntry
	1, // 1: edgelesssys.continuum.secret_service.userapi.UserAPI.SetSecrets:input_type -> edgelesssys.continuum.secret_service.userapi.SetSecretsRequest
	0, // 2: edgelesssys.continuum.secret_service.userapi.UserAPI.SetSecrets:output_type -> edgelesssys.continuum.secret_service.userapi.SetSecretsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_gpl_proto_secret_service_userapi_userapi_proto_init() }
func file_internal_gpl_proto_secret_service_userapi_userapi_proto_init() {
	if File_internal_gpl_proto_secret_service_userapi_userapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDesc), len(file_internal_gpl_proto_secret_service_userapi_userapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_gpl_proto_secret_service_userapi_userapi_proto_goTypes,
		DependencyIndexes: file_internal_gpl_proto_secret_service_userapi_userapi_proto_depIdxs,
		MessageInfos:      file_internal_gpl_proto_secret_service_userapi_userapi_proto_msgTypes,
	}.Build()
	File_internal_gpl_proto_secret_service_userapi_userapi_proto = out.File
	file_internal_gpl_proto_secret_service_userapi_userapi_proto_goTypes = nil
	file_internal_gpl_proto_secret_service_userapi_userapi_proto_depIdxs = nil
}
