// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/proto/secret-service/backendapi/backendapi.proto

package backendapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendAPI_AccessSecrets_FullMethodName = "/edgelesssys.continuum.secret_service.backendapi.BackendAPI/AccessSecrets"
)

// BackendAPIClient is the client API for BackendAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendAPIClient interface {
	AccessSecrets(ctx context.Context, in *AccessSecretsRequest, opts ...grpc.CallOption) (*AccessSecretsResponse, error)
}

type backendAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendAPIClient(cc grpc.ClientConnInterface) BackendAPIClient {
	return &backendAPIClient{cc}
}

func (c *backendAPIClient) AccessSecrets(ctx context.Context, in *AccessSecretsRequest, opts ...grpc.CallOption) (*AccessSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessSecretsResponse)
	err := c.cc.Invoke(ctx, BackendAPI_AccessSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendAPIServer is the server API for BackendAPI service.
// All implementations must embed UnimplementedBackendAPIServer
// for forward compatibility.
type BackendAPIServer interface {
	AccessSecrets(context.Context, *AccessSecretsRequest) (*AccessSecretsResponse, error)
	mustEmbedUnimplementedBackendAPIServer()
}

// UnimplementedBackendAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendAPIServer struct{}

func (UnimplementedBackendAPIServer) AccessSecrets(context.Context, *AccessSecretsRequest) (*AccessSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessSecrets not implemented")
}
func (UnimplementedBackendAPIServer) mustEmbedUnimplementedBackendAPIServer() {}
func (UnimplementedBackendAPIServer) testEmbeddedByValue()                    {}

// UnsafeBackendAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendAPIServer will
// result in compilation errors.
type UnsafeBackendAPIServer interface {
	mustEmbedUnimplementedBackendAPIServer()
}

func RegisterBackendAPIServer(s grpc.ServiceRegistrar, srv BackendAPIServer) {
	// If the following call pancis, it indicates UnimplementedBackendAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendAPI_ServiceDesc, srv)
}

func _BackendAPI_AccessSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendAPIServer).AccessSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendAPI_AccessSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendAPIServer).AccessSecrets(ctx, req.(*AccessSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendAPI_ServiceDesc is the grpc.ServiceDesc for BackendAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgelesssys.continuum.secret_service.backendapi.BackendAPI",
	HandlerType: (*BackendAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccessSecrets",
			Handler:    _BackendAPI_AccessSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/secret-service/backendapi/backendapi.proto",
}
