// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: internal/proto/secret-service/backendapi/backendapi.proto

package backendapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessSecretsRequest is the request sent by an attestation-agent to the Secret Service to join the deployment.
type AccessSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSecretsRequest) Reset() {
	*x = AccessSecretsRequest{}
	mi := &file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSecretsRequest) ProtoMessage() {}

func (x *AccessSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSecretsRequest.ProtoReflect.Descriptor instead.
func (*AccessSecretsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescGZIP(), []int{0}
}

// AccessSecretsResponse is the response sent by the Secret Service.
// It contains authentication credentials for the worker to interact with etcd, as well as additional configuration options.
type AccessSecretsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cert is a PEM encoded client certificate for the worker to interact with etcd.
	Cert []byte `protobuf:"bytes,1,opt,name=Cert,proto3" json:"Cert,omitempty"`
	// Key is a PEM encoded private key for the worker to interact with etcd.
	Key []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	// CACert is the PEM encoded CA certificate of the etcd server.
	CACert        []byte `protobuf:"bytes,3,opt,name=CACert,proto3" json:"CACert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSecretsResponse) Reset() {
	*x = AccessSecretsResponse{}
	mi := &file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSecretsResponse) ProtoMessage() {}

func (x *AccessSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSecretsResponse.ProtoReflect.Descriptor instead.
func (*AccessSecretsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescGZIP(), []int{1}
}

func (x *AccessSecretsResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *AccessSecretsResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AccessSecretsResponse) GetCACert() []byte {
	if x != nil {
		return x.CACert
	}
	return nil
}

var File_internal_proto_secret_service_backendapi_backendapi_proto protoreflect.FileDescriptor

var file_internal_proto_secret_service_backendapi_backendapi_proto_rawDesc = string([]byte{
	0x0a, 0x39, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x65, 0x64, 0x67,
	0x65, 0x6c, 0x65, 0x73, 0x73, 0x73, 0x79, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75,
	0x75, 0x6d, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x22, 0x16, 0x0a, 0x14,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x43, 0x65, 0x72,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x41, 0x43, 0x65, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x43, 0x41, 0x43, 0x65, 0x72, 0x74, 0x32, 0xad, 0x01, 0x0a, 0x0a,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x41, 0x50, 0x49, 0x12, 0x9e, 0x01, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x45, 0x2e, 0x65,
	0x64, 0x67, 0x65, 0x6c, 0x65, 0x73, 0x73, 0x73, 0x79, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x46, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x6c, 0x65, 0x73, 0x73, 0x73, 0x79,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x6c, 0x65,
	0x73, 0x73, 0x73, 0x79, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x75, 0x6d, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescOnce sync.Once
	file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescData []byte
)

func file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescGZIP() []byte {
	file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescOnce.Do(func() {
		file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_secret_service_backendapi_backendapi_proto_rawDesc), len(file_internal_proto_secret_service_backendapi_backendapi_proto_rawDesc)))
	})
	return file_internal_proto_secret_service_backendapi_backendapi_proto_rawDescData
}

var file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_secret_service_backendapi_backendapi_proto_goTypes = []any{
	(*AccessSecretsRequest)(nil),  // 0: edgelesssys.continuum.secret_service.backendapi.AccessSecretsRequest
	(*AccessSecretsResponse)(nil), // 1: edgelesssys.continuum.secret_service.backendapi.AccessSecretsResponse
}
var file_internal_proto_secret_service_backendapi_backendapi_proto_depIdxs = []int32{
	0, // 0: edgelesssys.continuum.secret_service.backendapi.BackendAPI.AccessSecrets:input_type -> edgelesssys.continuum.secret_service.backendapi.AccessSecretsRequest
	1, // 1: edgelesssys.continuum.secret_service.backendapi.BackendAPI.AccessSecrets:output_type -> edgelesssys.continuum.secret_service.backendapi.AccessSecretsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_secret_service_backendapi_backendapi_proto_init() }
func file_internal_proto_secret_service_backendapi_backendapi_proto_init() {
	if File_internal_proto_secret_service_backendapi_backendapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_secret_service_backendapi_backendapi_proto_rawDesc), len(file_internal_proto_secret_service_backendapi_backendapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_secret_service_backendapi_backendapi_proto_goTypes,
		DependencyIndexes: file_internal_proto_secret_service_backendapi_backendapi_proto_depIdxs,
		MessageInfos:      file_internal_proto_secret_service_backendapi_backendapi_proto_msgTypes,
	}.Build()
	File_internal_proto_secret_service_backendapi_backendapi_proto = out.File
	file_internal_proto_secret_service_backendapi_backendapi_proto_goTypes = nil
	file_internal_proto_secret_service_backendapi_backendapi_proto_depIdxs = nil
}
