services:
  chatgpt-web:
    container_name: chatgpt-web
    restart: always
    depends_on:
      - privatemode-proxy
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile

  privatemode-proxy:
    container_name: privatemode-proxy
    image: ghcr.io/edgelesssys/privatemode/privatemode-proxy:latest
    restart: always
    command: ["--apiKey", "<API-KEY-HERE>"]
    ports:
      - 8080:8080
